// src/components/Footer.vue
<template>
   <footer class="footer">
        <div class="container">
            <div class="columns">
                <div class="footer-logo logo column is-5">
                    <a href="/"><img src="img/logo.svg" style="height: 34px;" alt="logo" /></a>
                    <p class="small copyright has-text-light m-t-30">
                        PorphyStruct by <a href="/jens" class="has-text-light">Jens Krumsieck</a> <br/>
                        (2019 - {{new Date().getFullYear()}})
                    </p>
                    <p class="small made has-text-light m-t-5">
                        <svg xmlns="http://www.w3.org/2000/svg" height="16px" width="16px" viewBox="0 0 450 600" preserveAspectRatio="none"><rect width="753.578" height="508.953" x="0" y="0" fill="rgb(0, 0, 0)"></rect><rect width="753.578" height="339.30199999999996" x="0" y="169.65099999999998" fill="rgb(198, 12, 48)"></rect><rect width="753.578" height="169.65099999999998" x="0" y="339.30199999999996" fill="rgb(253, 200, 47)"></rect></svg>
                        Made in Germany
                    </p>
                </div>
                <div class="column footer-menu menu">
                    <p class="menu-label">PorphyStruct</p>
                    <ul class="menu-list">
                        <li>
                            <router-link :to="{path: '/'}"><b-icon pack="fa" icon="home" />  Home</router-link>
                        </li>
                        <li>
                            <router-link :to="{path: '/support'}"><b-icon pack="fa" icon="life-ring" />  Support</router-link>
                        </li>
                        <li>
                            <a href="https://github.com/JensKrumsieck/PorphyStruct/releases/latest/" target="_blank"><b-icon pack="fa" icon="cloud-download-alt" /> Download</a>
                        </li>
                        <li>
                            <router-link :to="{path: '/imprint'}"><b-icon pack="fa" icon="balance-scale" /> Imprint</router-link>
                        </li>
                    </ul>
                </div>
                 <div class="column footer-menu menu">
                    <p class="menu-label">PorphyStruct</p>
                    <ul class="menu-list">
                        <li>
                            <router-link :to="{path: '/'}"><b-icon pack="fa" icon="home" />  Home</router-link>
                        </li>
                        <li>
                            <router-link :to="{path: '/support'}"><b-icon pack="fa" icon="life-ring" />  Support</router-link>
                        </li>
                        <li>
                            <a href="https://github.com/JensKrumsieck/PorphyStruct/releases/latest/" target="_blank"><b-icon pack="fa" icon="cloud-download-alt" /> Download</a>
                        </li>
                        <li>
                            <router-link :to="{path: '/imprint'}"><b-icon pack="fa" icon="balance-scale" /> Imprint</router-link>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
   </footer>
</template>

<script>
export default {
  name: 'Footer',
  components: {
  }
}
</script>

// src/lib/components/Footer.svelte
<script>
	import Button from '$lib/components/common/Button.svelte';
	import Windows from 'svelte-material-icons/Windows.svelte';
	import Wrapper from '$lib/components/common/Wrapper.svelte';
	import H3 from '$lib/components/common/H3.svelte';
	import Badge from '$lib/components/common/Badge.svelte';
	import ContactJens from '$lib/components/ContactJens.svelte';
	import ContactMartin from '$lib/components/ContactMartin.svelte';
	import Container from './common/Container.svelte';
</script>

<footer class="mt-12">
	<Container>
		<svg
			class="absolute right-0 z-[-1] md:flex hidden"
			xmlns="http://www.w3.org/2000/svg"
			width="1363.724"
			height="483.796"
			viewBox="0 0 1363.724 483.796"
		>
			<path
				d="M668,4105.938c15.531-4.751,509.621-313.558,509.621-313.558L930.576,4105.938l247.045-147.277-49.884,180.533,118.772-73.638h767.265"
				transform="translate(-650.051 -3754.22)"
				fill="none"
				stroke="#0088bc"
				stroke-width="90"
			/>
		</svg>
		<Wrapper notFullHeight>
			<div class="md:w-1/3 w-full">
				<H3>Interested? Download now! It's Free!</H3>
				<div class="group">
					<Button
						_class="w-72"
						href="https://github.com/jenskrumsieck/porphystruct/releases/latest"
					>
						<Windows size="1.5rem" />
						<span> <span class="font-bold ml-2">Download </span> for Windows</span>
					</Button>

					<Button _class="w-48 my-3" href="https://app.porphystruct.org" outlined>
						<span class="font-bold">Webversion</span>
					</Button>
				</div>
			</div>
			<div class="logo-footer md:w-2/3 w-full md:mt-0 mt-10">
				<div class="flex md:place-content-end">
					<img src="/ps_logo.svg" alt="Logo" width="42px" />
					<span class="font-bold text-[1.75rem] ml-2 self-center">PorphyStruct</span>
				</div>
				<p class="flex md:place-content-end mt-4">
					<a href="/imprint">Legal Notice</a>
					<a class="ml-6" href="/privacy">Privacy Policy</a>
				</p>
			</div>
			<div class="flex flex-wrap bg-off-white rounded">
				<ContactJens />
				<ContactMartin />
			</div>
		</Wrapper>
	</Container>
</footer>
